spring.datasource.url=jdbc:mysql://localhost:3306/eventzen
spring.datasource.username=root
spring.datasource.password=Sravani9392

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8082
jwt.secret=yourSuperSecretKey123